apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: rabbitmq
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 5672
