apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server
spec:
  selector:
    matchLabels:
      app: rest-server
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      containers:
      - name: rest-server
        image: gcr.io/final-recycling-project/rest-server:0.6
        env:
          - name: RABBITMQ_HOST
            value: "10.3.252.34"
          - name: POSTGRES_HOST
            value: "10.3.250.193"
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: gcr-secret